# Generated by Django 5.0.1 on 2024-01-27 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pimg', models.ImageField(upload_to='media/')),
                ('pcity', models.CharField(max_length=255)),
                ('pstate', models.CharField(max_length=80)),
                ('paddress_line', models.CharField(max_length=1000)),
                ('plandmark', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('sprice', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('is_rent', models.BooleanField(default=False)),
                ('is_south', models.BooleanField(default=False)),
                ('is_north', models.BooleanField(default=False)),
                ('is_east', models.BooleanField(default=False)),
                ('is_south_east', models.BooleanField(default=False)),
                ('is_north_east', models.BooleanField(default=False)),
                ('is_1', models.BooleanField(default=False)),
                ('is_2', models.BooleanField(default=False)),
                ('is_3', models.BooleanField(default=False)),
                ('has_boundary_wall', models.BooleanField(default=False)),
                ('is_corner_plot', models.BooleanField(default=False)),
                ('is_gated_property', models.BooleanField(default=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('smsg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.plot')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('password', models.CharField(max_length=120)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('messages', models.ManyToManyField(blank=True, related_name='user_messages', to='v0.contact')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_plots', to='v0.user'),
        ),
        migrations.CreateModel(
            name='UserPlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.plot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.user')),
            ],
        ),
    ]
