# Generated by Django 5.0.1 on 2024-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_alter_plot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='is_sub_user',
            field=models.BooleanField(default=False),
        ),
    ]
