# Generated by Django 5.0.1 on 2024-02-21 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0003_plot_is_sub_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('message', models.TextField()),
            ],
        ),
    ]
