# Generated by Django 5.0.2 on 2024-03-04 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0006_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=15)]),
        ),
    ]
