# Generated by Django 5.0.1 on 2024-04-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0013_alter_user_sub_end_alter_user_sub_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='sprice',
            field=models.BigIntegerField(null=True),
        ),
    ]
